-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gcd]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Gcd.Types
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
open gcd

/- [core::num::{u8}::trailing_zeros]:
   Source: '/rustc/library/core/src/num/uint_macros.rs', lines 152:8-152:48
   Name pattern: [core::num::{u8}::trailing_zeros] -/
axiom core.num.U8.trailing_zeros : U8 → Result U32

